cam_model: Pinhole
cam_width: 1280
cam_height: 1080
scale: 1.0
# cam_fx: 386.08279418945312
# cam_fy: 386.1546630859375
# cam_cx: 669.1446533203125
# cam_cy: 551.7761535644531
cam_fx: 408.08279418945312
cam_fy: 408.1546630859375
cam_cx: 626.1446533203125
cam_cy: 563.7761535644531
cam_d0: 0.03074293
cam_d1: -0.0386573
cam_d2: 0.00022112
cam_d3: -0.0008439
cam_d4: 0.0
cam_d5: 0.0
cam_d6: 0.0
cam_d7: 0.0
cam_d8: 0.0
cam_d9: 0.0
cam_d10: 0.0
cam_d11: 0.0
cam_d12: 0.0
cam_d13: 0.0
